name: Release and Publish to npm

on:
  release:
    types: [created]

jobs:
  release-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Configure Git identity
        run: |
          git config --global user.email "guyllkegen@gmail.com"
          git config --global user.name "Kegen Guyll"

      - name: Run semantic release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release

      - name: Publish to npm
        if: github.event.release.draft == false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
